### ISSUE TITLE
Supprimer la croix devant chaque événement

### ISSUE THREAD

**Issue by Bowlazed** [byteclubfr/bc-planner#15]
Cette croix ne fait qu'alourdir la lisibilité. Elle n'a pas de signification précise. Autant ne rien mettre.
En revanche, il faut laisser la coche devant les événements ayant reçu validation.

**Comment by Bowlazed** [comment]
Les croix sont revenues d'entre les morts !

**Comment by Delapouite** [comment]
soucis de deploiement.
