### ISSUE TITLE
La navigation entre les colonnes mois est cassée

### ISSUE THREAD

**Issue by Bowlazed** [byteclubfr/bc-planner#19]
Cliquer sur les boutons latéraux de navigation ne permet plus de décaler l'affichage d'un mois vers la gauche ou vers la droite.
Ce qui se passe maintenant, est que ça ajoute une colonne mois à gauche, quand on clique sur le bouton gauche. Et ça ajoute 2 à droite et supprime une à gauche quand on clique sur le bouton droit.
(omportement non stable, j'ai constater des variantes en essayant plusieurs fois)

**Comment by Delapouite** [comment]
réparé  → probleme de getMonth()
