### ISSUE TITLE
 Le champs select nb de mois à afficher bloque l'appli.

### ISSUE THREAD

**Issue by Bowlazed** [byteclubfr/bc-planner#21]
Quand on clique pour changer le nombre de colonnes mois à afficher, l'appli se fige, jusqu'à finalement proposer d'actualiser la page.

**Comment by Bowlazed** [comment]
Ça fonctionne !

**Comment by Delapouite** [comment]
Boucles infinies probables : 
https://github.com/byteclubfr/bc-planner/blob/master/app/utils/date.js#L42-L45
https://github.com/byteclubfr/bc-planner/blob/master/app/utils/date.js#L56-L59
