### ISSUE TITLE
Les tags n'apparaissent pas lors de l'édition d'un event.

### ISSUE THREAD

**Issue by Bowlazed** [byteclubfr/bc-planner#22]

**Comment by Bowlazed** [comment]
Les tags sont revenus !

**Comment by Delapouite** [comment]
https://github.com/byteclubfr/bc-planner/commit/962f3c051ab2fd5b50ca677049f6a809a28fb24f

**Comment by Bowlazed** [comment]
Le problème est toujours là. En tout cas sous chrome + Mac.
![bc planner](https://cloud.githubusercontent.com/assets/2757708/20352610/2546c5cc-ac18-11e6-8dfd-2bc92d7289aa.png)
