### ISSUE TITLE
Des événements qui viennent d'être créés disparaissent du Planner...

### ISSUE THREAD

**Issue by Bowlazed** [byteclubfr/bc-planner#28]
Aujourd'hui, plusieurs événements que je venais de créer ont disparu du Planner.
Voyant cela, je les ai re-créés.
Ils ont encore disparu.
Pourtant, dans l'agenda Google Byteclub, je les vois, tous.

**Comment by Delapouite** [comment]
https://github.com/byteclubfr/bc-planner/commit/114c188a39cf477df9a0d61a512d34311917677d
